name: Queue
version: '${version}'
main: club.crestmc.queue.Queue
api-version: 1.16
authors: [ Blurmit ]
description: A simple queue plugin
softdepend:
  - Basics
  - LuckPerms
permissions:
  queue.join:
    default: true
  queue.leave:
    default: true
